### ISSUE TITLE
Cannot find Raspberry Pi Pico Siwat's Light Control Protocol Firmware

### ISSUE THREAD

**Issue by Bruyant** [SiwatINC/slcp-audiovideosync#1]
Hi,

I'm looking for this firmware but cannot find it anywere.

Regards,
Nicolas

**Comment by SiwatS** [comment]
Hello, you can download firmware.uf2 at
https://github.com/SiwatINC/siwat-light-control-protocol-firmware
Or compile it yourself using platformio
